version: '3'
services:
  started:
    image: rankey/auth:latest
    ports:
      - 3500
    deploy:
      labels:
        - "traefik.backend=auth"
        - "traefik.frontend.rule=Host:auth.devcrew.com.co"