version: '3'
services:
  started:
    build: auth:1.0.0
    ports:
      - 3500
    deploy:
      labels:
        - "traefik.backend=started"
        - "traefik.frontend.rule=Host:auth.devcrew.com.co"